# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline=true

# ~/.config/starship.toml

[kubernetes]
disabled = false


[nix_shell]
disabled = true
